#
# Copyright (C) 2018-2019 Simonas Tamošaitis <tamosaitis.simonas@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for strongSwan

LUCI_DEPENDS:=+strongswan-default
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
